language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t avolpe89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true avolpe89/docker-react npm run test